---
# file: site.yml
# description: Ansible playbook for bootstrapping fresh macOS installs.

- hosts: local

  pre_tasks:
    - import_tasks: roles/common/tasks/whoami.yml
    - import_tasks: roles/common/tasks/home_subdirs.yml

  roles:
    - setup
    - plists
    - homebrew
    - ssh
    - zsh
    - dotfiles
    - pip
