---
- homebrew: update_homebrew=yes upgrade_all=yes

- homebrew: name={{ item }} state=present
  with_items: "{{ homebrew_packages }}"

- homebrew: name={{ item.key }} state=present install_options={{ item.value }}
  with_dict: "{{ homebrew_custom_packages }}"
